pool:
  vmImage: 'Ubuntu 16.04'

stages:
- stage: CI
  jobs: 
  - job: 'Build_And_Test'
    steps:
    - script: cd complete && ./gradlew build
      displayName: build stage
    - script:  cd complete && ./gradlew test
      displayName: test stage
    - task: SonarSource.sonarcloud.14d9cde6-c1da-4d55-aa01-2965cd301255.SonarCloudPrepare@1
  displayName: 'Prepare analysis on SonarCloud'
  inputs:
    SonarCloud: SonarCloudConexion
    organization: danieltoro165051
    scannerMode: Other

