pool:
  vmImage: 'Ubuntu 16.04'

stages:
- stage: CI
  jobs: 
  - job: 'Build_And_Test'
    steps:
    - script: cd complete && ./gradlew bootRun
      displayName: build stage
    - script:  cd complete && ./gradlew test
      displayName: test stage
  
    
    
    
    
    
    
    
    
    
    
    
=======
- stage: Obtain_Source_Code
  jobs:
  - job: A1
    displayName: Obtener Codigo fuente
    steps:
    - bash: echo $JAVA_HOME
    
- stage: Build_Spring_Boot_App
  jobs:
  - job: B1
    displayName: Compilar Aplicación
    steps:
    - bash: echo "A"
    
- stage: Execute_Unit_Tests
  jobs:
  - job: B1
    displayName: Ejecutar Pruebas unitarias con Gradle
    steps:
    - bash: echo "A"
    
- stage: Static_Code_Analyzer
  jobs:
  - job: B1
    displayName: Analisis de Codigo con SonarQube
    steps:
    - bash: echo "A"
>>>>>>> 6812f729c7689a377df6cc14783f994921149dc2
