pool:
  vmImage: 'Ubuntu 16.04'

stages:
- stage: CI
  jobs: 
  - job: 'Build_And_Test'
    steps:
    - script: cd complete && ./gradlew build
      displayName: build stage
    - script:  cd complete && ./gradlew test
      displayName: test stage
    - task: SonarCloudPrepare@1
      inputs:
        SonarCloud: 'SonarCloudConexion'
        organization: 'danieltoro165051'
        scannerMode: 'Other'
    - task: Gradle@2
      inputs:
        gradleWrapperFile: 'complete'
        workingDirectory: 'complete'
        tasks: 'AnalisisDeCodigoSonarC'
        publishJUnitResults: false
        javaHomeOption: 'JDKVersion'
        sonarQubeRunAnalysis: true
        sqGradlePluginVersionChoice: 'build'
    - task: SonarCloudPublish@1
      inputs:
        pollingTimeoutSec: '300'

