pool:
  vmImage: 'Ubuntu 16.04'

stages:
- stage: CI
  jobs: 
  - job: 'Build_And_Test'
    steps:
    - script: cd complete && ./gradlew build
      displayName: build stage
    - script:  cd complete && ./gradlew test
      displayName: test stage
    - task: SonarCloudPrepare@1
      inputs:
        SonarCloud: 'SonarCloudConexion'
        organization: 'danieltoro165051'
        scannerMode: 'Other'
    - task: SonarCloudAnalyze@1
    - task: SonarCloudPublish@1
      inputs:
        pollingTimeoutSec: '300'

