pool:
  vmImage: 'Ubuntu 16.04'

stages:
- stage: CI
  jobs: 
  - job: 'Build_And_Test'
    steps:
    - script: cd complete && ./gradlew build
      displayName: build stage
    - script:  cd complete && ./gradlew test
      displayName: test stage

